import {
  LayoutDashboard,
  FileText,
  Package,
  Users,
  ShieldCheck,
  CreditCard,
  Settings,
  Bell,
  BarChart3,
  Globe,
  Wallet,
  Tags,
  LifeBuoy,
} from "lucide-react";
export const adminNavigation = [
  ["dashboard", "Overview", LayoutDashboard],
  ["buyers", "Buyers", Users],
  ["sellers", "Suppliers", Users],
  ["kyc", "KYC review", ShieldCheck],
  ["products", "Product listings", Package],
  ["categories", "Categories", Tags],
  ["leads", "Lead management", FileText],
  ["subscriptions", "Subscription plans", CreditCard],
  ["payments", "Payments", Wallet],
  ["protection", "Buyer protection", ShieldCheck],
  ["claims", "Claims & disputes", LifeBuoy],
  ["refunds", "Refund tracking", Wallet],
  ["cms", "Website content", Globe],
  ["reports", "Reports & analytics", BarChart3],
  ["notifications", "Notifications", Bell],
  ["settings", "Settings", Settings],
] as const;
